

export const creators = [
    {id:1, nome: 'TeamJHZ', src: '', tiktok: 'https://www.tiktok.com/@teamjhz', categorie: ['Gaming'] },
    {id:2, nome: 'PreTattica_official', src: '', tiktok: 'https://www.tiktok.com/@pretattica_official', categorie: ['Sport'] },
    {id:3, nome: 'Fantaballa', src: '', tiktok: 'https://www.tiktok.com/@fantaballa', categorie: ['Gaming'] },
    {id:4, nome: 'davi_ambro', src: '', tiktok: 'https://www.tiktok.com/@davi_ambro', categorie: ['Vlog personali'] },
    { id:5, nome: 'TonyilSalumiere', src: '', tiktok: 'https://www.tiktok.com/@tonyilsalumiere', categorie: ['Gaming', 'Sport', 'Intrattenimento'] },
    { id:6,nome: 'Michelapilatti', src: '', tiktok: 'https://www.tiktok.com/@michelapilatti', categorie: ['Vlog personali'] },
    {id:7, nome: 'Mattia_deiTaluni', src: '', tiktok: 'https://www.tiktok.com/@mattia_deitaluni', categorie: ['Vlog personali', 'Musica e Canto', 'Sport', 'Altro'] },
    {id:8, nome: 'Giankooo', src: '', tiktok: 'https://www.tiktok.com/@giankooo', categorie: ['Vlog personali'] },
    { id:9,nome: '123StellaOfficial', src: '', tiktok: 'https://www.tiktok.com/@123stellaofficial', categorie: ['Gaming'] },
    { id:10,nome: 'sub_zero410', src: '', tiktok: 'https://www.tiktok.com/@andrien1102', categorie: ['Gaming'] },
    { id:11,nome: 'AndreSawi', src: '', tiktok: 'https://www.tiktok.com/@andresawi', categorie: ['Gaming'] },
    { id:12,nome: 'Ciuffo Gamer', src: '', tiktok: 'https://www.tiktok.com/@ciuffogamer', categorie: ['Gaming'] },
    {id:13, nome: 'Sank_Ace', src: '', tiktok: 'https://www.tiktok.com/@sank_ace', categorie: ['Gaming'] },
    { id:14,nome: 'Claudia', src: '', tiktok: 'https://www.tiktok.com/@claudietta_fn', categorie: ['Gaming', 'Vlog personali'] },
    {id:15, nome: 'RosyBerty', src: '', tiktok: 'https://www.tiktok.com/@rosyberty', categorie: ['Viaggi e Avventure', 'Recensioni e Unboxing', 'Vlog personali', 'Animali'] },
    { id:16,nome: 'NonnoErotiko', src: '', tiktok: 'https://www.tiktok.com/@nonnoerotiko', categorie: ['Vlog personali', 'Balli e Coreografie'] },
    { id:17,nome: 'Gianmarco Fede', src: '', tiktok: 'https://www.tiktok.com/@giamm4fed3', categorie: ['Gaming'] },
    { id:18,nome: 'Ludo.tet', src: '', tiktok: 'https://www.tiktok.com/@ludo.tet', categorie: ['Beauty e Makeup', 'Cucina', 'Vlog personali', 'Relazioni e Consigli di Coppia', 'Altro'] },
    { id:19,nome: 'thekinglisander', src: '', tiktok: 'https://www.tiktok.com/@thekinglisander', categorie: ['Gaming'] },
    { id:20,nome: 'io.numero.perfett', src: '', tiktok: 'https://www.tiktok.com/@io.numero.perfett', categorie: ['Vlog personali'] },
    { id:21,nome: 'ilCotto_cdk', src: '', tiktok: 'https://www.tiktok.com/@ilcotto_cdk', categorie: ['Vlog personali'] },
    { id:22,nome: 'angelabarone_', src: '', tiktok: 'https://www.tiktok.com/@angelabarone_', categorie: ['Vlog personali'] },
    { id:23,nome: 'la famiglia Nerd', src: '', tiktok: 'https://www.tiktok.com/@lafamiglianerd', categorie: ['Gaming'] },
    { id:24,nome: 'Carodecastello_TV', src: '', tiktok: 'https://www.tiktok.com/@carodecastello', categorie: ['Vlog personali', 'Balli e Coreografie'] },
    { id:25,nome: 'PartyTuning', src: '', tiktok: 'https://www.tiktok.com/@partytuning', categorie: ['Gaming'] },
    { id:26,nome: 'VeesKyyOnTiKToK', src: '', tiktok: 'https://www.tiktok.com/@veeskyyontiktok', categorie: ['Gaming'] },
    { id:27,nome: 'cuciniamoinsiemeacasaa', src: '', tiktok: 'https://www.tiktok.com/@cuciniamoinsiemeacasaa', categorie: ['Cucina', 'Vlog personali'] },
    {id:28, nome: 'Il fenomeno peter', src: '', tiktok: 'https://www.tiktok.com/@ilfenomenopeter', categorie: ['Vlog personali'] },
  ];